### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by aquintiliano** [codebutler/android-websockets#20]
05-19 12:30:01.670: E/AndroidRuntime(9231): FATAL EXCEPTION: websocket-thread
05-19 12:30:01.670: E/AndroidRuntime(9231): Process: com.mywebsockettest, PID: 9231
05-19 12:30:01.670: E/AndroidRuntime(9231): java.lang.NullPointerException
05-19 12:30:01.670: E/AndroidRuntime(9231):     at com.codebutler.android_websockets.WebSocketClient$3.run(WebSocketClient.java:245)
05-19 12:30:01.670: E/AndroidRuntime(9231):     at android.os.Handler.handleCallback(Handler.java:733)
05-19 12:30:01.670: E/AndroidRuntime(9231):     at android.os.Handler.dispatchMessage(Handler.java:95)
05-19 12:30:01.670: E/AndroidRuntime(9231):     at android.os.Looper.loop(Looper.java:136)
05-19 12:30:01.670: E/AndroidRuntime(9231):     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by rsclmumbai** [comment]
Any possibility of this being fixed?
I'm getting this error on Android 4.4.2 & 5.0

**Comment by DonLiangGit** [comment]
me too
