### ISSUE TITLE
Socket not connected

### ISSUE THREAD

**Issue by hoangsondev** [codebutler/android-websockets#26]
How to fix bugs?
 java.lang.IllegalStateException: Socket not connected
            at com.example.WebSocketClient$3.run(WebSocketClient.java:239)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:157)
            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ghost** [comment]
i have the same problem, do you find the solutions?

**Comment by ghost** [comment]
@hoangsondev 
I resolved.
you should use send in `onConnect()` .

**Comment by hoangsondev** [comment]
Thank @DaidongStudio very much!

**Comment by SrishtiRoy** [comment]
@hoangsondev  how did you solve it >> can any body help with snippet
